<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Models/ErrorViewModel.fs" />
    <Compile Include="Controllers/HomeController.fs" />
    <Compile Include="Startup.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PDDGB7_HFT_2023242.Logic\PDDGB7_HFT_2023242.Logic.csproj" />
    <ProjectReference Include="..\PDDGB7_HFT_2023242.Models\PDDGB7_HFT_2023242.Models.csproj" />
    <ProjectReference Include="..\PDDGB7_HFT_2023242.Repository\PDDGB7_HFT_2023242.Repository.csproj" />
  </ItemGroup>

</Project>
